version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: car_rental_bases
    environment:
      POSTGRES_DB: car_rental_service
      POSTGRES_USER: car
      POSTGRES_PASSWORD: rent
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data_rental_service

volumes:
  postgres_data: