spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: groupIdAccount
    topic:
      payment: paymentResponseTopic
      paymentResponse: paymentTopic

logging:
  level:
    root: info


